// <auto-generated />
namespace OrenburgTourismFM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Photo_Meeting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Photo_Meeting));
        
        string IMigrationMetadata.Id
        {
            get { return "201912231610164_Photo_Meeting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
